### ISSUE TITLE
Error after CLI-install

### ISSUE THREAD

**Issue by Zeppen** [tomhnatt/net.tomheine.flexit#1]
Hi there!

I got tempted to install your Homey app. I have a similar setup but it doesn't seem to work.
Installation via CLI was all good but after that Im lost. Maybe some modbus communication error is the problem here?

Please see attatched screenshot of my installation.
![image](https://user-images.githubusercontent.com/1380001/194777427-92cf212b-83e0-4702-b653-8e0472f0e207.png)
After some seconds I see this
![image](https://user-images.githubusercontent.com/1380001/194777647-efdc715c-4700-48cc-a1ae-9470c4de90bd.png)
"the device is not avaliable" 

the USR-TCP232-410S seems to communicate 
![image](https://user-images.githubusercontent.com/1380001/194777826-ce8f9c3c-1507-4069-b597-1f796ef3c4a8.png)
with the Flexit (i have the right pins, 16(+),17(-),18(gnd) in both ends of the cable :) ( i even skipped the cable and took the 16,17,18-pins directly to the USR-TCP232-410S to avoid any bad connection between the Flexit and the USR-TCP232-410S , but no difference, still the same error in the Homey.

My settings of the USR-TCP232-410S are the same as yours..
![image](https://user-images.githubusercontent.com/1380001/194777814-1d5bd5b0-0ba4-4faf-9cbd-0a8141033cd3.png)

any ideas of what can cause the error?

Many thanx for developing the app so far 👍

**Comment by cscheiene** [comment]
@Zeppen I could not get it to work either. I looked at the wiring diagram for my Nordic S4 and found that the right modbus for me was on pins 14, 15, 16. Changed it and worked fine

**Comment by vegargrim** [comment]
@cscheiene Do you know if the correct wiring is modbus slave D+ (16), modbus slave D- (17) and signal ground (18)?

I have started purchasing what I need for this. But the guide could be clearer on where the wires should be connected.

According the manual on the wiring adapter, pin 14 is digital or analog input, pin 15 is digital input X8 and pin 16 is modbus slave D+.

Thanks for the help!

**Comment by cscheiene** [comment]
![IMG_20240222_182732_edit_865630218747600](https://github.com/tomhnatt/net.tomheine.flexit/assets/22115237/77dfe94c-6f31-439e-b993-af641717f0ea)
Check you diagram for your unit if you have it. Modbus slave was on T12 connector on the main board, which goes to 14,15,16, on the ext1 connector.  I don't have the original flexit cable adapter by the way, just bought an 20pin atx cable for about 100NOK

**Comment by tomhnatt** [comment]
The guide is only made for the cable adaptor, and with that it connects to 16, 17 and 18 (se page 8 for description with modbus references):  https://www.flexit.no/globalassets/catalog/documents/man_116468_4659.pdf

I have not tried to connect directly to motherboard.

**Comment by tomhnatt** [comment]
> any ideas of what can cause the error?
> 
> Many thanx for developing the app so far 👍

Did you make sure to change the IP-addres in the source code?

**Comment by vegargrim** [comment]
@cscheiene Thanks! I will check the wiring if I encounter any issues with following what the guide says. Still waiting for the TCP232.

@tomhnatt Thanks for the reply. I bought the flexit cable adapter, so I will stick with 16, 17 and 18. But what threw me off was this line on the guide.
«Oppdatert: Enkelte har erfart at portene ikke er de samme på alle aggregater. Sjekk ditt aggregat sin manual. Flere har erfart at det er 14, 15 og 16 som skal benyttes.»

**Comment by cscheiene** [comment]
@vegargrim if you use the original cable follow the guide. I'm just saying that if you skip the cable and connect directly to ext1 (the connector the adapter plugs in to) you can't use the diagram for the cable adaptor because it looks like 16,17,18 does not go to the same pins on the ext1 side. And from my diagram for the unit itself it's pin 14,15,16 on the ext1 connector

**Comment by vegargrim** [comment]
@cscheiene Aha, that makes sense. Thank you for the explination! Looking forward to setting this up and going away from the homeassistant variant im using now.

**Comment by tomhnatt** [comment]
Updated the guide with information of use without cable adaptor.
